import type {
  Exercise,
  WorkoutSession,
  UserProfile,
  FitnessMetricPoint,
  Challenge,
  UserSettings,
} from '@/types';

export const MOCK_USER: UserProfile = {
  id: 'usr_01',
  name: 'Marcus Vance',
  email: 'marcus@example.com',
  athleteLevel: 'Intermediate',
  experienceYears: 2,
  targetGoal: 'Build Muscle',
  weightKg: 81.5,
  heightCm: 183,
  joinedDate: '2026-01-15',
  streakDays: 14,
  weeklyProgressScore: 92,
};

export const MOCK_EXERCISES: Exercise[] = [
  {
    id: 'ex_squats',
    name: 'Squats',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Core'],
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    trackingType: 'reps',
    instructions: [
      'Stand with feet shoulder-width apart, toes pointing slightly outward.',
      'Engage your core and lower your hips down and back as if sitting into a chair.',
      'Lower until your thighs are parallel to the floor while keeping your chest upright.',
      'Drive through your heels to return to the starting standing position.',
    ],
    formTips: [
      'Keep your knees tracking over your toes and avoid caving inward',
      'Keep your chest lifted and spine neutral throughout the movement',
      'Keep both heels firmly planted on the floor',
    ],
    commonMistakes: [
      'Knees caving inward during the ascent',
      'Rounding the lower back or collapsing chest forward',
      'Heels lifting off the ground',
    ],
    targetRepsDefault: 12,
    targetSetsDefault: 3,
  },
  {
    id: 'ex_pushups',
    name: 'Push-Ups',
    muscleGroup: 'Chest',
    secondaryMuscles: ['Arms', 'Shoulders', 'Core'],
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    trackingType: 'reps',
    instructions: [
      'Start in a high plank position with hands placed slightly wider than shoulder-width.',
      'Keep your body in a rigid straight line from head to heels by bracing your core and glutes.',
      'Lower your chest toward the floor until your elbows reach approximately a 90-degree angle.',
      'Press firmly through your palms to return to the starting position with elbows softly extended.',
    ],
    formTips: [
      'Keep elbows angled at roughly 45 degrees, avoiding flaring them out wide',
      'Maintain a flat back without letting your hips sag or hike up',
      'Exhale as you push back up to the starting position',
    ],
    commonMistakes: [
      'Sagging hips or hyperextending lower back',
      'Flaring elbows out to 90 degrees',
      'Incomplete depth or half-reps without full chest travel',
    ],
    targetRepsDefault: 15,
    targetSetsDefault: 3,
  },
  {
    id: 'ex_lunges',
    name: 'Lunges',
    muscleGroup: 'Legs',
    secondaryMuscles: ['Core'],
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    trackingType: 'reps',
    instructions: [
      'Stand upright with feet hip-width apart and your hands resting on your hips or in front of your chest.',
      'Step forward with one leg and lower your hips until both knees bend at approximately 90 degrees.',
      'Ensure your front knee stays aligned above your ankle, not shooting far beyond your toes.',
      'Push through your front foot to return to the standing position, then alternate legs.',
    ],
    formTips: [
      'Keep your torso tall and upright with eyes facing forward',
      'Lower your back knee smoothly toward the floor without slamming',
      'Distribute weight evenly across the midfoot and heel of the front leg',
    ],
    commonMistakes: [
      'Leaning the torso excessively forward',
      'Front knee caving inward past the big toe',
      'Taking a step too short, causing severe knee strain',
    ],
    targetRepsDefault: 10,
    targetSetsDefault: 3,
  },
  {
    id: 'ex_jumping_jacks',
    name: 'Jumping Jacks',
    muscleGroup: 'Full Body',
    secondaryMuscles: ['Legs', 'Shoulders'],
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    trackingType: 'reps',
    instructions: [
      'Stand upright with your feet together and arms resting naturally at your sides.',
      'Jump feet outward slightly wider than shoulder-width while raising arms overhead.',
      'Jump back to the initial stance by bringing feet together and lowering arms.',
      'Maintain a steady, rhythmic bounce on the balls of your feet.',
    ],
    formTips: [
      'Land softly on the balls of your feet with knees slightly soft to absorb shock',
      'Bring arms all the way overhead for complete shoulder range of motion',
      'Keep a continuous, controlled breathing cadence',
    ],
    commonMistakes: [
      'Landing flat-footed with heavy impact on knees and ankles',
      'Only raising arms halfway up',
      'Losing posture and hunching the upper back',
    ],
    targetRepsDefault: 30,
    targetSetsDefault: 3,
  },
  {
    id: 'ex_plank',
    name: 'Plank',
    muscleGroup: 'Core',
    secondaryMuscles: ['Shoulders', 'Back'],
    difficulty: 'Beginner',
    equipment: 'Bodyweight',
    trackingType: 'duration',
    targetDurationSeconds: 45,
    instructions: [
      'Place your forearms on the floor with elbows aligned directly beneath your shoulders.',
      'Extend both legs straight behind you, resting securely on the balls of your feet.',
      'Engage your abdominal wall, glutes, and quadriceps to hold a straight line from crown to heels.',
      'Hold the posture steadily while maintaining calm, continuous breathing.',
    ],
    formTips: [
      'Keep your neck neutral by gazing gently at the floor between your forearms',
      'Pull your belly button inward toward your spine and squeeze your glutes tight',
      'Avoid holding your breath; take calm, rhythmic breaths throughout the hold',
    ],
    commonMistakes: [
      'Sagging hips, putting compressive stress on the lumbar spine',
      'Piking the hips up into a triangle shape',
      'Straining the neck by looking up or hanging the head low',
    ],
    targetRepsDefault: 1,
    targetSetsDefault: 3,
  },
];

export const MOCK_WORKOUT_HISTORY: WorkoutSession[] = [
  {
    id: 'wk_01',
    title: 'Full Body Foundation',
    description: 'Squats, Push-Ups, and Plank hold',
    startTime: '2026-10-04T07:30:00Z',
    endTime: '2026-10-04T08:15:00Z',
    durationMinutes: 45,
    averageFormScore: 94,
    caloriesBurned: 380,
    totalVolumeKg: 0,
    status: 'completed',
    exercises: [
      {
        exerciseId: 'ex_squats',
        exercise: MOCK_EXERCISES[0],
        sets: [
          { setNumber: 1, reps: 12, completed: true, accuracyScore: 96 },
          { setNumber: 2, reps: 12, completed: true, accuracyScore: 94 },
          { setNumber: 3, reps: 12, completed: true, accuracyScore: 93 },
        ],
      },
      {
        exerciseId: 'ex_pushups',
        exercise: MOCK_EXERCISES[1],
        sets: [
          { setNumber: 1, reps: 15, completed: true, accuracyScore: 95 },
          { setNumber: 2, reps: 15, completed: true, accuracyScore: 92 },
          { setNumber: 3, reps: 12, completed: true, accuracyScore: 94 },
        ],
      },
      {
        exerciseId: 'ex_plank',
        exercise: MOCK_EXERCISES[4],
        sets: [
          { setNumber: 1, reps: 1, durationSeconds: 45, completed: true, accuracyScore: 96 },
          { setNumber: 2, reps: 1, durationSeconds: 45, completed: true, accuracyScore: 95 },
          { setNumber: 3, reps: 1, durationSeconds: 40, completed: true, accuracyScore: 92 },
        ],
      },
    ],
  },
  {
    id: 'wk_02',
    title: 'Lower Body & Conditioning',
    description: 'Lunges, Squats, and Jumping Jacks',
    startTime: '2026-10-02T17:15:00Z',
    endTime: '2026-10-02T17:55:00Z',
    durationMinutes: 40,
    averageFormScore: 91,
    caloriesBurned: 350,
    totalVolumeKg: 0,
    status: 'completed',
    exercises: [
      {
        exerciseId: 'ex_lunges',
        exercise: MOCK_EXERCISES[2],
        sets: [
          { setNumber: 1, reps: 10, completed: true, accuracyScore: 92 },
          { setNumber: 2, reps: 10, completed: true, accuracyScore: 90 },
          { setNumber: 3, reps: 10, completed: true, accuracyScore: 91 },
        ],
      },
      {
        exerciseId: 'ex_jumping_jacks',
        exercise: MOCK_EXERCISES[3],
        sets: [
          { setNumber: 1, reps: 30, completed: true, accuracyScore: 94 },
          { setNumber: 2, reps: 30, completed: true, accuracyScore: 90 },
          { setNumber: 3, reps: 30, completed: true, accuracyScore: 89 },
        ],
      },
    ],
  },
];

export const MOCK_METRIC_POINTS: FitnessMetricPoint[] = [
  {
    date: '2026-09-08',
    weightKg: 82.8,
    bodyFatPercent: 14.8,
    avgFormScore: 88,
    workoutDurationMinutes: 45,
    volumeKg: 22500,
    repsCount: 160,
  },
  {
    date: '2026-09-15',
    weightKg: 82.4,
    bodyFatPercent: 14.5,
    avgFormScore: 90,
    workoutDurationMinutes: 50,
    volumeKg: 24200,
    repsCount: 180,
  },
  {
    date: '2026-09-22',
    weightKg: 82.0,
    bodyFatPercent: 14.2,
    avgFormScore: 92,
    workoutDurationMinutes: 52,
    volumeKg: 25800,
    repsCount: 195,
  },
  {
    date: '2026-09-29',
    weightKg: 81.7,
    bodyFatPercent: 13.9,
    avgFormScore: 93,
    workoutDurationMinutes: 55,
    volumeKg: 27400,
    repsCount: 210,
  },
  {
    date: '2026-10-05',
    weightKg: 81.5,
    bodyFatPercent: 13.6,
    avgFormScore: 94,
    workoutDurationMinutes: 55,
    volumeKg: 28200,
    repsCount: 220,
  },
];

export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: 'ch_01',
    title: 'Squat Form Perfection',
    category: 'Form Quality',
    goal: 'Complete 50 squat sets with a form score above 90%',
    description: 'Focus on proper depth, straight back, and knee tracking over 30 days.',
    targetValue: 50,
    currentValue: 38,
    unit: 'Sets',
    deadline: 'Oct 31, 2026',
    rewardBadge: 'Form Master',
    participantsCount: 840,
    status: 'active',
    isJoined: true,
  },
  {
    id: 'ch_02',
    title: 'October Volume Challenge',
    category: 'Workout Volume',
    goal: 'Lift 100,000 kg total volume this month',
    description: 'Stay consistent across all workouts and accumulate weight safely.',
    targetValue: 100000,
    currentValue: 68400,
    unit: 'kg',
    deadline: 'Oct 31, 2026',
    rewardBadge: 'Iron Lifter',
    participantsCount: 1250,
    status: 'active',
    isJoined: true,
  },
  {
    id: 'ch_03',
    title: '21-Day Workout Consistency',
    category: 'Consistency',
    goal: 'Complete at least 3 workouts each week for 3 weeks',
    description: 'Build an unbreakable workout habit with consistent training.',
    targetValue: 9,
    currentValue: 6,
    unit: 'Workouts',
    deadline: 'Oct 25, 2026',
    rewardBadge: 'Consistency Champion',
    participantsCount: 520,
    status: 'active',
    isJoined: true,
  },
  {
    id: 'ch_04',
    title: 'Push-Up Mastery',
    category: 'Form Quality',
    goal: 'Complete 300 push-ups with verified clean form',
    description: 'Keep your core engaged and lock out smoothly on each rep.',
    targetValue: 300,
    currentValue: 0,
    unit: 'Reps',
    deadline: 'Nov 15, 2026',
    rewardBadge: 'Push-Up Pro',
    participantsCount: 390,
    status: 'available',
    isJoined: false,
  },
];

export const MOCK_SETTINGS: UserSettings = {
  voiceGuidance: true,
  vibrationAlerts: true,
  formStrictness: 'Standard',
  unitSystem: 'Metric (kg)',
  emailNotifications: true,
  theme: 'dark',
};
